### ISSUE TITLE
Figure out implementation and design details for security requests, interpreters; possibly also in-hospital transportation

### ISSUE THREAD

**Issue by Kdoje** [Azure-Abominable-Snowman/cs3733teama#128]

**Comment by oats-penko** [comment]
continuing to work on interpreter details - creating multiple tables, making classes; added generic classes to hold info that will be similar to all staff as well as specific interp staff

**Comment by oats-penko** [comment]
See comments on other issue regarding Interpreter requests; this is pretty much done.
