### ISSUE TITLE
Create the program code to allow the admins to add modify remove the list of service people in the database

### ISSUE THREAD

**Issue by Kdoje** [Azure-Abominable-Snowman/cs3733teama#143]

**Comment by oats-penko** [comment]
currently working on the interpreter staff database; likely going to create a separate database for staff contact info... deciding to make staffID based on an auto-incremented column in the login database; this staffID will link to all the necessary db tables for staff info and requests

**Comment by oats-penko** [comment]
databases set up, tests done

**Comment by Kdoje** [comment]
I can do the UI(s) and controller code for this
