### ISSUE TITLE
Admin/Staff security request within the hospital

### ISSUE THREAD

**Issue by mebroughton** [Azure-Abominable-Snowman/cs3733teama#144]

**Comment by oats-penko** [comment]
Making Request class abstract. Adding InterpreterRequest and SecurityRequest as child classes of Request. RequestSubsystem class is singleton, will make all appropriate database accesses. Working on redesign of classes and general organization of Request subsystem.

**Comment by oats-penko** [comment]
Request Interface instead of abstract Request class.

**Comment by oats-penko** [comment]
Won't work. The tracking information for each request type is too diverse to combine. Only similarities are the generic information filling - location, etc.

**Comment by oats-penko** [comment]
Making the Interpreter Request subsystem - includes databases for interpreter requests, interpreter reports, and interpreter staff. A Singleton will be used as a Facade to interact with the service request feature. Request Priority Level obsolete.  
In future -- perhaps make a staff 'mailbox' to hold the requests that are assigned to a particular staff member.

**Comment by oats-penko** [comment]
finishing up methods for making interpreter requests and storing/accessing them through the database; going to make an interpreter staff db

**Comment by oats-penko** [comment]
finalized details for Interpreter Request. Will update class diagram soon. Have all three databases set up but they still need to be tested. Made Singleton for interfacing with the interpreter database (staff and request)

**Comment by oats-penko** [comment]
Cleaned up some classes that were no longer needed.
