### ISSUE TITLE
css for the new UI / update the FXMLs to reflect updated UI

### ISSUE THREAD

**Issue by oats-penko** [Azure-Abominable-Snowman/cs3733teama#204]

**Comment by Kdoje** [comment]
As a user I want to use a professionally stylized UI so I can understand how to use the application easier

**Comment by Kdoje** [comment]
I've finished the formatting for the staff editor and the request view. We still need the Main Screen, Directions and Map editor

**Comment by Kdoje** [comment]
All done except for API and settings
